# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_curso', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dia_Semana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.Dia_Semana')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_materia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_professor', models.CharField(max_length=50)),
                ('materia', models.ManyToManyField(to='grade.Materia')),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sala', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.IntegerField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.Curso')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.Semestre')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='turma',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.Turno'),
        ),
        migrations.AddField(
            model_name='grade',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.Horario'),
        ),
        migrations.AddField(
            model_name='grade',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.Materia'),
        ),
        migrations.AddField(
            model_name='grade',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.Sala'),
        ),
        migrations.AddField(
            model_name='grade',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.Turma'),
        ),
        migrations.AddField(
            model_name='curso',
            name='materia',
            field=models.ManyToManyField(to='grade.Materia'),
        ),
    ]
