# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='materia',
            field=models.ManyToManyField(blank=True, to='grade.Materia'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='materia',
            field=models.ManyToManyField(blank=True, to='grade.Materia'),
        ),
    ]
